# Generated by Django 5.2.4 on 2026-03-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='institutional_docs/')),
                ('category', models.CharField(choices=[('POLICY', 'Policy'), ('HANDBOOK', 'Student Handbook'), ('FORM', 'Official Form'), ('TUTORIAL', 'Tutorial/Guide')], default='POLICY', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True, help_text='Visible to all students')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
