version: '3.8'

x-test-build: &test-build
  args:
    INSTALL_TEST: "true"

services:
  api_gateway:
    build:
      <<: *test-build
      context: ../api_gateway
  
  auth_service:
    build:
      <<: *test-build
      context: ../services/auth_service

  patient_service:
    build:
      <<: *test-build
      context: ../services/patient_service

  doctor_service:
    build:
      <<: *test-build
      context: ../services/doctor_service

  appointment_service:
    build:
      <<: *test-build
      context: ../services/appointment_service

  billing_service:
    build:
      <<: *test-build
      context: ../services/billing_service

  pharmacy_service:
    build:
      <<: *test-build
      context: ../services/pharmacy_service

  lab_service:
    build:
      <<: *test-build
      context: ../services/lab_service

  ward_service:
    build:
      <<: *test-build
      context: ../services/ward_service

  emergency_service:
    build:
      <<: *test-build
      context: ../services/emergency_service

  ambulance_service:
    build:
      <<: *test-build
      context: ../services/ambulance_service

  hr_service:
    build:
      <<: *test-build
      context: ../services/hr_service

  maintenance_service:
    build:
      <<: *test-build
      context: ../services/maintenance_service

  radiology_service:
    build:
      <<: *test-build
      context: ../services/radiology_service

  notification_service:
    build:
      <<: *test-build
      context: ../services/notification_service

  analytics_service:
    build:
      <<: *test-build
      context: ../services/analytics_service
