name: Deploy Static Site to EC2 via Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to EC2 with Docker
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            git clone https://github.com/Thamizh-S24/AWS-DEVOPS.git
            cd AWS-DEVOPS/DevOps/CICD/jenkins-cicd2
            docker stop static-container || true
            docker rm static-container || true
            docker build -t static-image .
            docker run -d --name static-container -p 80:80 static-image
          EOF
