apiVersion: apps/v1
kind: Deployment
metadata:
  name: learnhub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: learnhub
  template:
    metadata:
      labels:
        app: learnhub
    spec:
      containers:
      - name: learnhub
        image: thamizh2026devops/learnhub:latest
        ports:
        - containerPort: 8000
        env:
        - name: ALLOWED_HOSTS
          value: "127.0.0.1,localhost,learnhub.local"
