# Generated by Django 5.2.4 on 2026-03-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('SYSTEM', 'System Alert'), ('COURSE', 'Course Update'), ('ANNOUNCEMENT', 'Announcement')], default='ANNOUNCEMENT', max_length=20)),
                ('target_group', models.CharField(choices=[('ALL', 'All Users'), ('STUDENTS', 'All Students'), ('INSTRUCTORS', 'All Instructors'), ('SPECIFIC', 'Specific User')], default='ALL', max_length=20)),
                ('link', models.CharField(blank=True, help_text='Optional URL to redirect user when clicked', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-notification__created_at'],
            },
        ),
    ]
