pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building the Project......'
                sh 'ls -l'
            }
        }

        stage('Test') {
            steps {
                echo 'Testing the Project......'
                sh 'cat index.html'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying the Project......'
                sh 'echo "Deployed the project Successfully"'
            }
        }
    }
}
