pipeline {
	agent any 
		stages {
			stage('Build') {
				step {
					echo 'Building the Project......'
					sh 'ls -l'
			}
		}
			stage('Test') {
				step {
					echo 'Testing the Project......'
					sh 'cat index.html'
			}
		}
			stage('Deploy'){
				step {
					echo 'Deploying the Project......'
					sh 'echo "Deployed the project Successfully'			}
			}
		}
	}
	
}
