# Generated by Django 5.2.4 on 2026-03-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='award', help_text='Lucide icon name', max_length=50)),
                ('criteria_type', models.CharField(choices=[('COURSE', 'Course Completion'), ('QUIZ', 'High Quiz Score'), ('ACTIVITY', 'Community Activity')], max_length=20)),
                ('criteria_value', models.IntegerField(default=1, help_text='e.g., number of courses, or min score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
