# Generated by Django 5.2.4 on 2026-03-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Learn Hub', max_length=100)),
                ('contact_email', models.EmailField(default='support@learnhub.com', max_length=254)),
                ('footer_text', models.CharField(default='© 2026 Learn Hub. All rights reserved.', max_length=255)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('primary_color', models.CharField(default='#4f46e5', max_length=7)),
                ('accent_color', models.CharField(default='#818cf8', max_length=10)),
                ('enable_ai_recommendations', models.BooleanField(default=True)),
                ('enable_dropout_detection', models.BooleanField(default=True)),
                ('enable_ai_quiz_generation', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Global Site Settings',
            },
        ),
    ]
