pipeline {
    agent any

    environment {
        DOCKER_BUILDKIT = '0'
    }

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Stop Existing Containers') {
            steps {
                dir('HEALIX_HMS') {
                    sh 'docker-compose down || true'
                }
            }
        }

        stage('Build Services') {
            steps {
                dir('HEALIX_HMS') {
                    sh 'docker-compose build --no-cache'
                }
            }
        }

        stage('Start Services') {
            steps {
                dir('HEALIX_HMS') {
                    sh 'docker-compose up -d'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('HEALIX_HMS/services/auth_service') {
                    sh 'pip install -r requirements.txt'
                    sh 'pip install -r requirements-test.txt'
                    sh 'pytest tests/'
                }
            }
        }

        stage('Verify Deployment') {
            steps {
                dir('HEALIX_HMS') {
                    sh 'docker-compose ps'
                }
            }
        }
    }

    post {
        success {
            echo 'Deployment successful!'
        }
        failure {
            echo 'Deployment failed!'
        }
    }
}
