sonar.projectKey=healix-hms
sonar.projectName=Healix HMS
sonar.projectVersion=1.0

# Scan all Python files in the repository
sonar.sources=.
sonar.python.version=3
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=**/node_modules/**, **/venv/**, **/tests/**, **/migrations/**, frontend/build/**

# Coverage reporting
sonar.python.coverage.reportPaths=coverage/coverage-hms_auth.xml,coverage/coverage-hms_gateway.xml
